# Generated by Django 3.2.5 on 2022-04-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=100)),
                ('front_pic_url', models.CharField(max_length=200)),
                ('front_count', models.IntegerField()),
                ('back_pic_url', models.CharField(max_length=200)),
                ('back_count', models.IntegerField()),
                ('happy', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
