# Generated by Django 3.2.5 on 2022-04-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Capture',
            new_name='Record',
        ),
    ]
