# Generated by Django 3.2.5 on 2022-04-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_rename_capture_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='location_gps_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='location_gps_lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='phone_info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
