# Generated by Django 3.2.5 on 2022-04-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0003_auto_20220425_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
