# Generated by Django 3.2.5 on 2022-05-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0004_record_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='timestamp',
            new_name='timestamp_upload',
        ),
        migrations.RemoveField(
            model_name='record',
            name='phone_info',
        ),
        migrations.RemoveField(
            model_name='record',
            name='username',
        ),
        migrations.AddField(
            model_name='record',
            name='loc_pic_url',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='processed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='timestamp_process',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='user_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='back_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='front_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='happy',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='location_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
