# Generated by Django 3.2.5 on 2022-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0005_auto_20220507_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='back_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='front_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='happy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='location_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='location_gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='location_gps_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp_process',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
