# Generated by Django 3.2.5 on 2022-05-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0006_auto_20220509_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user_id',
        ),
    ]
