# Generated by Django 3.2.5 on 2022-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0007_remove_record_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
