# Generated by Django 3.2.5 on 2022-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0008_record_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('location_gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_gps_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
